root: true
extends:
 - "eslint:recommended"
 - airbnb
 - "plugin:unicorn/recommended"
 - "plugin:promise/recommended"
plugins:
 - json
 - unicorn
 - "async-await"
 - "prefer-object-spread"
 - promise
env:
 browser: true
 node: true
"parserOptions":
  "sourceType": "module"
  "ecmaVersion": 8
  "ecmaFeatures":
    "experimentalObjectRestSpread": true
rules:
 "unicorn/filename-case": 0
 "no-console": 1
 "async-await/space-after-async": 2
 "async-await/space-after-await": 2
 "prefer-object-spread/prefer-object-spread": 2
